name: Build and Deploy

on:
  workflow_dispatch:  # This triggers the workflow manually from GitHub UI
#on:
#  push:
#    branches:
#      - main  # or specify your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 21 with Temurin
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Do wrapper
        run: gradle wrapper
      - name: Build JAR file with Gradle
        run: ./gradlew build --no-daemon
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        run: docker build -t teststubs .
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image
        run: docker push teststubs
